services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    _instanceof:
        Divante\MagentoIntegrationBundle\Application\Mapper\Strategy\MapStrategyInterface:
            tags: [object_mapper.mapStrategy]
        Divante\MagentoIntegrationBundle\Application\Mapper\Strategy\ClassificationStore\MapKeyStrategyInterface:
            tags: [object_mapper_classificationstore.mapStrategy]
        Divante\MagentoIntegrationBundle\Application\Mapper\Strategy\Custom\CustomStrategyInterface:
            tags: [object_mapper.customStrategy]

    Divante\MagentoIntegrationBundle\Action\Mapper\:
        resource: '../../Action/Mapper'
        public: true

    Divante\MagentoIntegrationBundle\Application\Mapper\MapperService:
        arguments: ['@Divante\MagentoIntegrationBundle\Application\Mapper\MapperContext', '@debug.event_dispatcher']

    Divante\MagentoIntegrationBundle\Application\Mapper\MapperContext: ~
    Divante\MagentoIntegrationBundle\Application\Mapper\MapperManager: ~

    Divante\MagentoIntegrationBundle\Application\Mapper\MapperColumnsService:
        arguments:
            - !tagged_iterator object_mapper.customStrategy

    Divante\MagentoIntegrationBundle\Application\Mapper\Strategy\MapClassificationStoreValue:
        arguments:
            - !tagged_iterator  object_mapper_classificationstore.mapStrategy

    Divante\MagentoIntegrationBundle\Application\Mapper\Strategy\:
        resource: '../../Application/Mapper/Strategy'

    Divante\MagentoIntegrationBundle\Application\Mapper\Strategy\ClassificationStore\:
        resource: '../../Application/Mapper/Strategy/ClassificationStore'
