imports:
- { resource: operators.yml }
- { resource: mapper.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    _instanceof:
        Divante\MagentoIntegrationBundle\Application\Common\IntegratedElementServiceInterface:
            tags: [magento_integration.remote_element.service]

# Action
    Divante\MagentoIntegrationBundle\Action\Rest\:
        resource: '../../Action/Rest'
        exclude: '../../Action/Rest/*/Type'
        public: true
        tags: ['controller.service_arguments']

    # Domain
    Divante\MagentoIntegrationBundle\Application\ElementDeleteService:
        arguments:
            - !tagged_iterator magento_integration.remote_element.service
    Divante\MagentoIntegrationBundle\Application\RemoteElementService:
        arguments:
            - !tagged_iterator magento_integration.remote_element.service

### Asset
    Divante\MagentoIntegrationBundle\Infrastructure\Asset\EventListener\AssetListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.asset.postUpdate, method: onPostAssetUpdate, priority: 50 }
        public: true

    Divante\MagentoIntegrationBundle\Application\Asset\AssetStatusService: ~
    Divante\MagentoIntegrationBundle\Application\Asset\IntegratedAssetService:
        calls:
            - [setContainer, ["@service_container"]]

### Category
    Divante\MagentoIntegrationBundle\Application\Category\CategoryStatusService: ~
    Divante\MagentoIntegrationBundle\Application\Category\CategoryValidator: ~
    Divante\MagentoIntegrationBundle\Application\Category\IntegratedCategoryService:
        calls:
            - [setContainer, ["@service_container"]]
    Divante\MagentoIntegrationBundle\Application\Category\MappedCategoryService: ~

### Common
    Divante\MagentoIntegrationBundle\Application\Common\StatusService: ~

### DataObject
    Divante\MagentoIntegrationBundle\Infrastructure\DataObject\DataObjectEventListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd,     method: onPreUpdate,  priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate,  method: onPreUpdate,  priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd,    method: onPostUpdate, priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate, priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete, method: onPostDelete, priority: 50 }
        public: true

### IntegrationConfiguration
    Divante\MagentoIntegrationBundle\Infrastructure\IntegrationConfiguration\IntegrationConfigurationListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate,  method: onPreUpdate,  priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd,     method: onPreUpdate,  priority: 50 }

    Divante\MagentoIntegrationBundle\Infrastructure\IntegrationConfiguration\IntegrationConfigurationRepository: ~
    Divante\MagentoIntegrationBundle\Application\IntegrationConfiguration\IntegrationConfigurationService: ~
    Divante\MagentoIntegrationBundle\Application\IntegrationConfiguration\IntegrationConfigurationValidator: ~

### Product
    Divante\MagentoIntegrationBundle\Application\Product\IntegratedProductService:
        calls:
            - [setContainer, ["@service_container"]]
    Divante\MagentoIntegrationBundle\Application\Product\MappedProductService: ~
    Divante\MagentoIntegrationBundle\Application\Product\ProductStatusService: ~
    Divante\MagentoIntegrationBundle\Application\Product\ProductValidatorService: ~

# Installer
    Divante\MagentoIntegrationBundle\Migrations\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('DivanteMagentoIntegrationBundle')"


# Providers
    Divante\MagentoIntegrationBundle\Domain\Provider\:
        resource: '../../Domain/Provider'
        public: true

    Divante\MagentoIntegrationBundle\Domain\Provider\MagentoRestOutputProvider:
        arguments:
            - "@file_locator"

    magento2_integration.storeprovider:
        class: Divante\MagentoIntegrationBundle\Domain\Provider\MagentoStore
        public: true

# Resolver
    Divante\MagentoIntegrationBundle\Resolver\RequestDTOResolver:
        arguments:
            - '@validator'
        tags:
            - { name: controller.request_value_resolver, priority: 50 }

# Responder
    Divante\MagentoIntegrationBundle\Responder\JsonResponder: ~
    Divante\MagentoIntegrationBundle\Responder\MappedObjectJsonResponder: ~

# Rest
    Divante\MagentoIntegrationBundle\Infrastructure\Rest\RestClient:
      public: true

    Divante\MagentoIntegrationBundle\Rest\RestClientBuilder:
      public: true

# Security
    Divante\MagentoIntegrationBundle\Infrastructure\Security\ElementPermissionChecker: ~
