imports:
- { resource: operators.yml }
- { resource: mapper.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    _instanceof:
        Divante\MagentoIntegrationBundle\Domain\Common\IntegratedElementServiceInterface:
            tags: [magento_integration.remote_element.service]

# Action
    Divante\MagentoIntegrationBundle\Action\Rest\:
        resource: '../../Action/Rest'
        public: true
        tags: ['controller.service_arguments']

    Divante\MagentoIntegrationBundle\Action\Admin\:
        resource: '../../Action/Admin'
        public: true
        tags: ['controller.service_arguments']

    # Domain
    Divante\MagentoIntegrationBundle\Domain\ElementDeleteService:
        arguments:
            - !tagged_iterator magento_integration.remote_element.service
    Divante\MagentoIntegrationBundle\Domain\RemoteElementService:
        arguments:
            - !tagged_iterator magento_integration.remote_element.service
### Admin
    Divante\MagentoIntegrationBundle\Domain\Admin\AbstactSendService: ~
    Divante\MagentoIntegrationBundle\Domain\Admin\SendProductsService: ~
    Divante\MagentoIntegrationBundle\Domain\Admin\SendCategoriesService: ~
    Divante\MagentoIntegrationBundle\Domain\Admin\CommandExcecutor: ~

### Asset
    Divante\MagentoIntegrationBundle\Domain\Asset\EventListener\AssetListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.asset.postUpdate, method: onPostAssetUpdate, priority: 50 }
        public: true

    Divante\MagentoIntegrationBundle\Domain\Asset\AssetStatusService: ~
    Divante\MagentoIntegrationBundle\Domain\Asset\IntegratedAssetService:
        calls:
            - [setContainer, ["@service_container"]]

### Category
    Divante\MagentoIntegrationBundle\Domain\Category\CategoryStatusService: ~
    Divante\MagentoIntegrationBundle\Domain\Category\CategoryValidator: ~
    Divante\MagentoIntegrationBundle\Domain\Category\IntegratedCategoryService:
        calls:
            - [setContainer, ["@service_container"]]
    Divante\MagentoIntegrationBundle\Domain\Category\MappedCategoryService: ~

### Common
    Divante\MagentoIntegrationBundle\Domain\Common\StatusService: ~

### DataObject
    Divante\MagentoIntegrationBundle\Domain\DataObject\DataObjectEventListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd,     method: onPreUpdate,  priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate,  method: onPreUpdate,  priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd,    method: onPostUpdate, priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate, priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete, method: onPostDelete, priority: 50 }
        public: true

### IntegrationConfiguration
    Divante\MagentoIntegrationBundle\Domain\IntegrationConfiguration\IntegrationConfigurationListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate,  method: onPreUpdate,  priority: 50 }
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd,     method: onPreUpdate,  priority: 50 }

    Divante\MagentoIntegrationBundle\Domain\IntegrationConfiguration\IntegrationConfigurationRepository: ~
    Divante\MagentoIntegrationBundle\Domain\IntegrationConfiguration\IntegrationConfigurationService: ~
    Divante\MagentoIntegrationBundle\Domain\IntegrationConfiguration\IntegrationConfigurationValidator: ~

### Product
    Divante\MagentoIntegrationBundle\Domain\Product\IntegratedProductService:
        calls:
            - [setContainer, ["@service_container"]]
    Divante\MagentoIntegrationBundle\Domain\Product\MappedProductService: ~
    Divante\MagentoIntegrationBundle\Domain\Product\ProductStatusService: ~
    Divante\MagentoIntegrationBundle\Domain\Product\ProductValidatorService: ~

# Installer
    Divante\MagentoIntegrationBundle\Migrations\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('DivanteMagentoIntegrationBundle')"


# Providers
    Divante\MagentoIntegrationBundle\Provider\:
        resource: '../../Provider'
        public: true

    Divante\MagentoIntegrationBundle\Provider\MagentoRestOutputProvider:
        arguments:
            - "@file_locator"

    magento2_integration.storeprovider:
        class: Divante\MagentoIntegrationBundle\Provider\MagentoStore
        public: true

# Resolver
    Divante\MagentoIntegrationBundle\Resolver\RequestDTOResolver:
        arguments:
            - '@validator'
        tags:
            - { name: controller.request_value_resolver, priority: 50 }

# Responder
    Divante\MagentoIntegrationBundle\Responder\JsonResponder: ~
    Divante\MagentoIntegrationBundle\Responder\MappedObjectJsonResponder: ~

# Rest
    Divante\MagentoIntegrationBundle\Rest\RestClient:
      public: true

    Divante\MagentoIntegrationBundle\Rest\RestClientBuilder:
      public: true

# Security
    Divante\MagentoIntegrationBundle\Security\ElementPermissionChecker: ~

#Command
    Divante\MagentoIntegrationBundle\Command\SendProductsMagentoCommand:
        tags:
            - { name: 'console.command', command: 'integration-magento:send:product' }

    Divante\MagentoIntegrationBundle\Command\SendCategoriesMagentoCommand:
        tags:
            - { name: 'console.command', command: 'integration-magento:send:category' }
