imports:
- { resource: listeners.yml }
- { resource: requestServices.yml }
- { resource: operators.yml }
- { resource: mapper.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Divante\MagentoIntegrationBundle\Service\MapperService:
        public: true

    Divante\MagentoIntegrationBundle\Service\RestClient:
      public: true

    Divante\MagentoIntegrationBundle\Service\RestClientBuilder:
      public: true
    Divante\MagentoIntegrationBundle\Provider\ClassList:
      public: true

    Divante\MagentoIntegrationBundle\Service\IntegrationConfigurationService:
      public: true

    Divante\MagentoIntegrationBundle\Service\IntegratedObjectService:
      public: true

    Divante\MagentoIntegrationBundle\Model\Webservice\Service:
      public: true


    Divante\MagentoIntegrationBundle\Service\Product\ProductStatusService:
      public: true
      calls:
        - [setContainer, ["@service_container"]]

    Divante\MagentoIntegrationBundle\Service\Product\ProductService:
      public: true
      calls:
        - [setContainer, ["@service_container"]]

    Divante\MagentoIntegrationBundle\Service\Category\CategoryService:
      public: true
      calls:
        - [setContainer, ["@service_container"]]

    Divante\MagentoIntegrationBundle\Service\Category\CategoryStatusService:
      public: true
      calls:
        - [setContainer, ["@service_container"]]

    Divante\MagentoIntegrationBundle\Resolver\RequestDTOResolver:
        arguments:
            - '@validator'
        tags:
            - { name: controller.request_value_resolver, priority: 50 }

    Divante\MagentoIntegrationBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Divante\MagentoIntegrationBundle\Migrations\Installer:
        public: true
        arguments:
          $bundle: "@=service('kernel').getBundle('DivanteMagentoIntegrationBundle')"

    Divante\MagentoIntegrationBundle\Event\DeleteEventObjectFactory:
        public: true

    Divante\MagentoIntegrationBundle\Provider\RestOutputProviderInterface:
        class: Divante\MagentoIntegrationBundle\Provider\MagentoRestOutputProvider
        public: true
        arguments:
          - "@file_locator" 
    magento2_integration.storeprovider:
      class: Divante\MagentoIntegrationBundle\Provider\MagentoStore
      public: true

    Divante\MagentoIntegrationBundle\Provider\ClassificationStore:
      public: true
    Divante\MagentoIntegrationBundle\Provider\MagentoStore:
      public: true

    Divante\MagentoIntegrationBundle\Provider\ActiveLanguages:
        public: true

    Divante\MagentoIntegrationBundle\Event\IntegratedObjectEventFactory: ~
